name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '10.22.1'

    - name: Install Dependencies
      run: |
        npm install -g bower gulp karma
        npm install phantomjs
        npm install
        bower install

    - name: Run Script
      run: bash ./travis-script.sh

env:
  GH_REF: github.com/volumio/Volumio2-UI.git
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}